Tracker:AddLocations("locations/Athens.json")
Tracker:AddLocations("locations/San Francisco.json")
Tracker:AddLocations("locations/Nairobi.json")
Tracker:AddLocations("locations/Paris.json")
Tracker:AddLocations("locations/Rio de Janeiro.json")
Tracker:AddLocations("locations/Sydney.json")
Tracker:AddLocations("locations/Moscow.json")
Tracker:AddLocations("locations/Rome.json")
Tracker:AddLocations("locations/New York.json")
Tracker:AddLocations("locations/Mexico City.json")
Tracker:AddLocations("locations/Cairo.json")
Tracker:AddLocations("locations/Buenos Aires.json")
Tracker:AddLocations("locations/London.json")
Tracker:AddLocations("locations/Beijing.json")
Tracker:AddLocations("locations/Tokyo.json")
